### ISSUE TITLE
map / reduce / filter explanations

### ISSUE THREAD

**Issue by john-science** [theJollySin/python_for_scientists#78]
Today in class, there was a lot of confusion about what an iterator is, and why you might want to use map/reduce/filter.

So, that tells me [this lecture](https://github.com/john-science/python_for_scientists/blob/main/classes/05_lists_and_lambdas/lecture_05.md) could use some better explanations.

**Comment by dpham-materials** [comment]
I thought two things really helped my understanding of why iterators are useful, which were:
1) The inquiry about why iterators are more useful in terms of memory than other options. Rereading the lecture, I see where it asks "why bother keeping the whole thing in memory?" but it didn't really click to me what that could mean until some more complex examples were presented. From someone with a non-CS background, it's a little difficult for me to understand how the data is "stored" when not in use - It's taking me a little bit to understand how data is stored in a container (hard drive instead of memory?), and how an iterator accesses that container instead of storing all of the values in memory. 
2) The example of the "long" function being impossible to run, and being able to run it on an iterator. I think that's a useful practical example that's still able to be visualized.

**Comment by mrzachsnyder** [comment]
Re: iterators I think David said it well. How things are stored in memory was a big lightbulb for me.

For map/reduce/filter all I needed was that brief explanation of how map/reduce/filter are so ubiquitous in the data science world that the benevolent dictator and his team just added those functions to python.

**Comment by john-science** [comment]
Hey guys, tell me if these changes work for you:

https://github.com/john-science/python_for_scientists/commit/fda721846a9ac118eda638822ad43f294403d164

Thanks!

**Comment by dpham-materials** [comment]
> Hey guys, tell me if these changes work for you:
> 
> [fda7218](https://github.com/john-science/python_for_scientists/commit/fda721846a9ac118eda638822ad43f294403d164)
> 
> Thanks!

I like these changes! I would add a bit more about how exactly the "generator" knows which item to output at a given time (per my comment above about keeping things in other forms of storage?) but maybe that's getting too technical.

**Comment by mrzachsnyder** [comment]
Awesome, very thorough explanation of both iterators and map/reduce/filter. Thank you!
